CREATE TABLE IF NOT EXISTS user_streaks (
  user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  current_streak INTEGER NOT NULL DEFAULT 0,
  longest_streak INTEGER NOT NULL DEFAULT 0,
  total_check_ins INTEGER NOT NULL DEFAULT 0,
  last_check_in_date DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE user_streaks
ADD COLUMN IF NOT EXISTS current_streak INTEGER NOT NULL DEFAULT 0;

ALTER TABLE user_streaks
ADD COLUMN IF NOT EXISTS longest_streak INTEGER NOT NULL DEFAULT 0;

ALTER TABLE user_streaks
ADD COLUMN IF NOT EXISTS total_check_ins INTEGER NOT NULL DEFAULT 0;

ALTER TABLE user_streaks
ADD COLUMN IF NOT EXISTS last_check_in_date DATE;

ALTER TABLE user_streaks
ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE user_streaks
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS user_streak_checkins (
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  check_in_date DATE NOT NULL,
  reward_coins INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, check_in_date)
);

ALTER TABLE user_streak_checkins
ADD COLUMN IF NOT EXISTS check_in_date DATE;

ALTER TABLE user_streak_checkins
ADD COLUMN IF NOT EXISTS reward_coins INTEGER NOT NULL DEFAULT 0;

ALTER TABLE user_streak_checkins
ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE INDEX IF NOT EXISTS user_streak_checkins_user_date_idx
ON user_streak_checkins (user_id, check_in_date DESC);

CREATE UNIQUE INDEX IF NOT EXISTS user_streak_checkins_user_date_uidx
ON user_streak_checkins (user_id, check_in_date);
